version: '3'

services:
  web:
    build:
      context: .
    container_name: web
    # volumes: 
    #   - .:/app
    ports:
      - "3000:3000"


#     # command: npm run dev
   
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webclient.rule=Host(`0.0.0.0:3000`)"
      - "traefik.http.routers.webclient.tls=false"
      # - "traefik.http.routers.crmclient.tls.certresolver=letsencrypt"

networks:
  traefik_proxy:
    external: true
