import React, { useEffect, useState } from "react";
import BlogBody from "../../components/Blog/BlogBody";
import BlogFooter from "../../components/Blog/BlogFooter";
import BlogHeader from "../../components/Blog/BlogHeader";
import Footer from "../../components/home/Footer";
import { useDispatch, useSelector } from "react-redux";
import Header from "../../components/ui/Header";
// ;
import Head from "next/head";
import { selectBlogInformation } from "../../redux/blogSlice";
import { useRouter } from "next/router";
import axios from "axios";


// 

function BlogContent() { 

  const [blogData, setblogData] = useState([]);

  const router = useRouter()

  const {id} = router.query
  console.log(id, "#")


    //Medicine Categories
    const getBlogData = async () => {
      const { blogInformation } = axios
        .get(`https://murmuring-spire-64412.herokuapp.com/api/blogs/${id}`)
        .then((response) => {
          console.log(response.data);
          // dispatch(
          //   setMedicineInformation({
          //     blogInformation: response.data,
          //   })
          // );
          setblogData(response.data);
        })
        .catch(function (error) {
          if (error.response) {
            // Request made and server responded
            //dispatch(setAppointmentInfo(null));
  
            console.log(error.response.data);
            console.log(error.response.status);
            console.log(error.response.headers);
          } else if (error.request) {
            // The request was made but no response was received
            console.log(error.request);
          } else {
            // Something happened in setting up the request that triggered an Error
            console.log(error.message);
          }
        });
    };
  // Accessing the use Router
  useEffect(() => {
    // getBlogData();
  }, []);

  
  return (
    <>
    <div className="bg-gray-50">
      <Head>
        <title>Blog | Proxima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
     
      <main className="mx-auto max-w-7xl ">
        <section>
            {/* <div>
                <BlogHeader />
            </div> */}
            <div className="py-8">

            {/* {blogs?.map( (blog) => ( */}
      
       <BlogBody 
       key={blogData?.id}
       title={blogData?.title}
       FirstImage={blogData?.FirstImage}
       firstparagraph={blogData?.firstparagraph}
       SecondImage={blogData?.SecondImage}
       secondparagraph={blogData?.secondparagraph}
       ThirdImage={blogData?.ThirdImage} 
       thirdparagraph={blogData?.thirdparagraph}
       FourthImage={blogData?.FourthImage}
       fourthparagraph={blogData?.fourthparagraph} />

        {/* ))} */}
        
                
            </div>
            <div className="py-4">

            {/* {blogData?.map( (blog) => ( */}
       <BlogFooter 
       AuthorImage={blogData?.AuthorImage}
       authorname={blogData?.authorname}
       background={blogData?.background}
 />

        {/* ))} */}

            </div>
        </section>
        <section className="py-6">
          <Footer />
        </section>
      </main>
    </div>
    </>
  );
}

export default BlogContent;
