import React from "react";
import Head from "next/head";
import Header from "../components/ui/Header";
import Footer from "../components/home/Footer";
import InternShipForm from "../components/Internship/InternshipForm";


function internship() {
  return (
    <div className="bg-gray-50">
    <Head>
      <title>Internship | Proxima</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <section>
      <InternShipForm />
          <Footer />
        </section>
      </div>
  )
;
}

export default internship;
