import React from "react";
import Head from "next/head";
import Header from "../components/ui/Header";
import Footer from "../components/home/Footer";

function investment() {
  return (
    <div className="bg-gray-50">
    <Head>
      <title>Invest | Proxima</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <section>
          <Footer />
        </section>
      </div>
  )}

export default investment;
