import React, { useState } from "react";
import Head from "next/head";

function Blogs() {

  
  return (
    <div className="bg-gray-50">
      <Head>
        <title>Blog | Proxima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header />
     
      <main className="mx-auto divide-y divide-black">
         <section>
            <BlogHeader />
        
        </section> 
        <section className="py-6">
          <Footer />
        </section>
      </main>
       */}
    </div>
  );
}

export default Blogs;
