import React, { useState } from "react";
import BlogBody from "../components/Blog/BlogBody";
import BlogFooter from "../components/Blog/BlogFooter";
import BlogHeader from "../components/Blog/BlogHeader";
import Footer from "../components/home/Footer";
import { useDispatch, useSelector } from "react-redux";
import Header from "../components/ui/Header";
// ;
import Head from "next/head";
import { selectBlogInformation } from "../redux/blogSlice";



function BlogContent() {

  const blogs = useSelector(selectBlogInformation);

  
  return (
    <div className="bg-gray-50">
      <Head>
        <title>Blog | Proxima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
     
      <main className="mx-auto max-w-7xl ">
        <section>
            {/* <div>
                <BlogHeader />
            </div> */}
            <div className="py-8">

            {blogs?.map( (blog) => (
       <BlogBody 
       key={blod.id}
       title={blog.title}
       FirstImage={blog.FirstImage}
       firstparagraph={blog.firstparagraph}
       SecondImage={blog.SecondImage}
       secondparagraph={blog.secondparagraph}
       ThirdImage={blog.ThirdImage} 
       thirdparagraph={blog.thirdparagraph}
       FourthImage={blog.FourthImage}
       fourthparagraph={blog.fourthparagraph} />

        ))}
        
                
            </div>
            <div className="py-4">

            {blogs?.map( (blog) => (
       <BlogFooter 
       AuthorImage={blog.AuthorImage}
       authorname={blog.authorname}
       background={blog.background}
 />

        ))}

            </div>
        </section>
        <section className="py-6">
          <Footer />
        </section>
      </main>
    </div>
  );
}

export default BlogContent;
