import React from 'react'
import Head from "next/head";
import Header from '../components/ui/Header'
import DemoBanner from '../components/Demo/DemoBanner';
import Footer from '../components/home/Footer';

function demo() {
  return (
    <div className="bg-gray-50">
      <Head>
        <title>Demo | Proxima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* As ofnor there are two main demos the demo for school and one for ecommerce which will be potrayed here */}
      <main className='mx-auto max-w-7xl pt-12'> 
        <section>
        <DemoBanner />

        </section>
        <section>
          <Footer />
        </section>
      </main>
    </div>
  )
}

export default demo