import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Companies from '../components/utils/companies.jsx'
import WhyChooseUs from '../components/utils/whychooseus.jsx'
import LandingFeatures from '../components/landing/landingfeatures.jsx'
import Landing from '../components/landing/landing.jsx'
import BusinessAnalysis from '../components/landing/businessanalysis.jsx'
import Intergrations from '../components/landing/intergrations.jsx'
import Testimonials from '../components/landing/testimonials.jsx'
import Blog from '../components/landing/blog.jsx'
import TrackUser from '../components/utils/trackuser.jsx'

export default function Home() {
  return (
    <>
      <Head>
        <title>Proxima </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script type="text/javascript" src="/scripts/webflow.js"></script> 
        <script type="text/javascript" src="/scripts/scripts.js"></script> 
              
      </Head>
      <div className="page-wrapper">
        <main className="main-wrapper">
          <Landing />
          <Companies />
          <WhyChooseUs />
          <LandingFeatures />
          <div className="section-divider"></div>
          <BusinessAnalysis />
          <div className="section-divider is-bottom"></div>
          <Intergrations />
          <Testimonials />
          <Blog />
          <TrackUser />          
        </main>
      </div>
    </>
  );
}
