import Head from "next/head";
import React, { useRef, useEffect, useState } from "react";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Companies from '../components/utils/companies.jsx'
import WhyChooseUs from '../components/utils/whychooseus.jsx'
import LandingFeatures from '../components/landing/landingfeatures.jsx'
import Landing from '../components/landing/landing.jsx'
import BusinessAnalysis from '../components/landing/businessanalysis.jsx'
import Intergrations from '../components/landing/intergrations.jsx'
import Iframe from '../components/chatiframe/Iframe'
import SupportWindow from "../components/chatiframe/SupportWindow";
import Testimonials from '../components/landing/testimonials.jsx'
import Blog from '../components/landing/blog.jsx'
import TrackUser from '../components/utils/trackuser.jsx'



export default function Home() {
  const [visible, setVisible] = useState(false);
  const ref = useRef(null)

  useEffect(() => {
    function handleClickOutside(event) {
        if (ref.current && !ref.current.contains(event.target)) {
            setVisible(false)
        }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
        document.removeEventListener("mousedown", handleClickOutside);
    };
}, [ref])

  return (
    <>
      <Head>
        <title>Proxima </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        
        <link rel="icon" href="/favicon.ico" />
        <script type="text/javascript" src="/scripts/webflow.js"></script> 
        <script type="text/javascript" src="/scripts/scripts.js"></script> 
              
      </Head>
      <div className="page-wrapper">
        <main className="main-wrapper">
          <Landing />
          {/*<Companies />*/}
          <WhyChooseUs />
          <LandingFeatures />
          <div className="section-divider"></div>
          <BusinessAnalysis />
          <div className="section-divider is-bottom"></div>
          {/*<Intergrations />*/}
          {/*<Testimonials />
          {/*<Blog />*/}
          <TrackUser />  
          <div style={{
            width: '700px'
          }}>
            <div ref={ref} style={{
              width: '700px',
            }}>
              

                {/* <iframe frameBorder='0' border='0' cellSpacing='0' src="http://localhost:3001" style={{
                          position: 'fixed',
                          bottom: '24px',
                          right: '24px',
                          height: '60%',
                          width: '1700px',
                          borderStyle: 'none',
                      
                      }}></iframe>  */}
            </div> 
          </div>  
        </main>
      </div>
    </>
  );
}
